{% set name = "nerfacc" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nerfacc-{{ version }}.tar.gz
    sha256: 01850cbbd71b6aeab059cbfb695755f8b6604f3fdfe48c44925b4b97c0c324db

build:
  number: 2
  skip: true  # [cuda_compiler_version == "None"]
  skip: true  # [cuda_compiler_version == "11.8"]
  skip: true  # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("cuda") }}
    - {{ stdlib("c") }}
    - cmake
    - cuda-toolkit
    - ninja
    - pip         # [build_platform!= target_platform]
    - pybind11    # [build_platform!= target_platform]
    - python      # [build_platform!= target_platform]
    - pytorch     # [build_platform!= target_platform]
    - setuptools  # [build_platform!= target_platform]
  host:
    - cuda-version {{ cuda_compiler_version }}
    - cuda-toolkit
    - pip
    - python
    - pytorch
    - setuptools
  run:
    - cuda-cudart
    - python
    - pytorch
    - rich >=12
    - typing_extensions

test:
  imports:
    - nerfacc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nerfstudio-project/nerfacc
  summary: A General NeRF Acceleration Toolbox in PyTorch
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
